#!/bin/sh

# status bar
launch-polybar &
# wallpaper
nitrogen --restore &
# pipewire
pipewire &
pipewire-pulse &
wireplumber &
# compositor
picom &
# music player daemon
mpd &
# recording keyboard
screenkey --start-disabled &
# draw on screen
gromit-mpx &
# notification daemon
dunst &
# emojis 😂
emote &
# faster typing speed
xset r rate 150 30 &
